@startuml
class EventBusDefinitions <<static>> {
    + <<const>> NeedToChangeWindowContent : string = "NeedToChangeWindowContent"
    + <<const>> LoginedInAccount : string = "LoginedInAccount"
    + <<const>> OpenFriendsPageClicked : string = "OpenFriendsPageClicked"
    + <<const>> OpenChat : string = "OpenChat"
    + <<const>> OpenGroup : string = "OpenGroup"
    + <<const>> ChatCreated : string = "ChatCreated"
    + <<const>> TextMessageReceived : string = "TextMessageReceived"
}
@enduml
