@startuml
class CreationAccount {
    + Email : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
    + DisplayName : string <<get>> <<set>>
    + Username : string <<get>> <<set>>
}
@enduml
