@startuml
class UserControlEventBusArgs {
    + UserControlEventBusArgs(userControl:UserControl)
}
IEventBusArgs <|-- UserControlEventBusArgs
UserControlEventBusArgs --> "UserControl" UserControl
@enduml
