@startuml
class AuthorizationWindowViewModel {
    + AuthorizationWindowViewModel()
}
BaseViewModel <|-- AuthorizationWindowViewModel
AuthorizationWindowViewModel --> "CurrentWindowContent" UserControl
@enduml
