@startuml
class CreatePersonalChatViewModel {
    + CreatePersonalChatViewModel()
}
class "List`1"<T> {
}
BaseViewModel <|-- CreatePersonalChatViewModel
CreatePersonalChatViewModel --> "Users<UserViewModel>" "List`1"
CreatePersonalChatViewModel --> "LoadUsers" ICommand
@enduml
