@startuml
class FriendsPageViewModel {
    + SearchText : string <<get>> <<set>>
    + FriendsPageViewModel()
}
class "List`1"<T> {
}
BaseViewModel <|-- FriendsPageViewModel
FriendsPageViewModel --> "Users<UserViewModel>" "List`1"
FriendsPageViewModel --> "LoadUsers" ICommand
FriendsPageViewModel --> "Friends<UserViewModel>" "List`1"
FriendsPageViewModel --> "LoadFriends" ICommand
FriendsPageViewModel --> "AddFriend" ICommand
@enduml
