@startuml
class GroupPageViewModel {
    + MessageText : string <<get>> <<set>>
    +  <<event>> MessegesListChanged : Action 
    + SettingsDisplayName : string <<get>> <<set>>
    + SettingsDescription : string <<get>> <<set>>
    + RoleNameToCreate : string <<get>> <<set>>
    + UsernameToAdd : string <<get>> <<set>>
    + DragOver(dropInfo:IDropInfo) : void
    + Drop(dropInfo:IDropInfo) : void
    + GroupPageViewModel(group:GroupViewModel)
}
BaseViewModel <|-- GroupPageViewModel
IDropTarget <|-- GroupPageViewModel
GroupPageViewModel --> "_group" GroupViewModel
GroupPageViewModel --> "Group" GroupViewModel
GroupPageViewModel --> "SendMessageCommand" ICommand
GroupPageViewModel --> "SettingsPage" ContentControl
GroupPageViewModel --> "ChatVisibility" Visibility
GroupPageViewModel --> "SettingsVisibility" Visibility
GroupPageViewModel --> "OpenSettingsCommand" ICommand
GroupPageViewModel --> "CreateRoleCommand" ICommand
GroupPageViewModel --> "CurrentRolePage" ContentControl
GroupPageViewModel --> "RoleToConfigure" RoleToConfigureViewModel
GroupPageViewModel --> "EditRoleCommand" ICommand
GroupPageViewModel --> "SaveRoleEditChangesCommand" ICommand
GroupPageViewModel --> "CancelEditRoleCommand" ICommand
GroupPageViewModel --> "CloseSettingsCommand" ICommand
GroupPageViewModel --> "AddMemberCommand" ICommand
GroupPageViewModel --> "DeleteMemberCommand" ICommand
@enduml
