@startuml
class LoginPageViewModel {
    + Email : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + LoginPageViewModel()
}
BaseViewModel <|-- LoginPageViewModel
LoginPageViewModel --> "Login" ICommand
LoginPageViewModel --> "ChangeToRegisterWindow" ICommand
@enduml
