@startuml
class RolePermissionSettingsViewModel {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + IsAllowed : bool <<get>> <<set>>
}
BaseViewModel <|-- RolePermissionSettingsViewModel
@enduml
