@startuml
class RoleToConfigureViewModel {
    + Name : string <<get>> <<set>>
    + RoleToConfigureViewModel(role:RoleWithPermissions, allPermissions:List<ChatPermission>, members:List<User>, alreadyAssigned:List<User>)
    + GetChatPermissions() : List<ChatPermission>
}
class "List`1"<T> {
}
BaseViewModel <|-- RoleToConfigureViewModel
RoleToConfigureViewModel --> "Role" RoleWithPermissions
RoleToConfigureViewModel --> "Permissions<RolePermissionSettingsViewModel>" "List`1"
RoleToConfigureViewModel --> "Assignments<RoleAssignmentViewModel>" "List`1"
RoleToConfigureViewModel --> "AsignUserCommand" ICommand
@enduml
