@startuml
class UsernameConverter {
    + Convert(value:object, targetType:Type, parameter:object, culture:CultureInfo) : object
    + ConvertBack(value:object, targetType:Type, parameter:object, culture:CultureInfo) : object
}
IValueConverter <|-- UsernameConverter
@enduml
