@startuml
class MessageDto {
    + Id : int <<get>> <<set>>
    + ChatId : int <<get>> <<set>>
    + Chat : Chat? <<get>> <<set>>
    + SenderId : int <<get>> <<set>>
    + Sender : User? <<get>> <<set>>
    + RecipientId : int? <<get>> <<set>>
    + Recipient : User? <<get>> <<set>>
    + Data : string? <<get>> <<set>>
    + MediaUrl : string? <<get>> <<set>>
}
MessageDto --> "Timestamp" DateTime
@enduml
