@startuml
class AuthService {
    + IsAuthenticated : bool <<get>>
    + AccessToken : string <<get>>
    + AuthService()
    + <<async>> Login(email:string, password:string) : Task<bool>
    + <<async>> Register(accountData:CreationAccount) : Task<bool>
    + <<async>> Logout() : Task
}
IService <|-- AuthService
AuthService --> "User" User
@enduml
