@startuml
class GroupsServcie {
    + GroupsServcie()
    + <<async>> CreateGroup(chatDto:CreateGroupChatDto) : Task<ServiceResponse<Chat>>
    + <<async>> GetGroups() : Task<ServiceResponse<List<Chat>>>
    + <<async>> GroupModelToViewModel(group:Chat) : Task<GroupViewModel>
    + <<async>> DeleteMember(chatId:int, userId:int) : Task<ServiceResponse<bool>>
    + <<async>> AddMemberByUsername(chatId:int, username:string) : Task<ServiceResponse<ChatMember>>
    + <<async>> GetAllPermissions() : Task<ServiceResponse<List<ChatPermission>>>
}
IService <|-- GroupsServcie
@enduml
