@startuml
class PersonalChatsService {
    + PersonalChatsService()
    + <<async>> GetPersonalChatIfExistsOrCreateOne(parcipient:User) : Task<ChatViewModel>
    + <<async>> GetExistsPersonalChat(chatId:int) : Task<ChatViewModel>
    + <<async>> TryGetChatIfExists(chatId:int) : Task<ServiceResponse<Chat>>
    + <<async>> GetChatMessages(chatId:int) : Task<ObservableCollection<Message>>
}
IService <|-- PersonalChatsService
@enduml
