@startuml
!include .\\.\MessangerWithRoles.WPFClient\App.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\AssemblyInfo.puml
!include .\\.\MessangerWithRoles.WPFClient\GlobalVariables.puml
!include .\\.\MessangerWithRoles.WPFClient\Common\UsernameConverter.puml
!include .\\.\MessangerWithRoles.WPFClient\Data\APIEndpoints.puml
!include .\\.\MessangerWithRoles.WPFClient\Data\ChatTypeEnum.puml
!include .\\.\MessangerWithRoles.WPFClient\Data\PortList.puml
!include .\\.\MessangerWithRoles.WPFClient\Data\SocketResponseType.puml
!include .\\.\MessangerWithRoles.WPFClient\DTOs\AddChatMemberByUsernameDto.puml
!include .\\.\MessangerWithRoles.WPFClient\DTOs\CreateChatDto.puml
!include .\\.\MessangerWithRoles.WPFClient\DTOs\CreateGroupChatDto.puml
!include .\\.\MessangerWithRoles.WPFClient\DTOs\GroupChatInfoDto.puml
!include .\\.\MessangerWithRoles.WPFClient\DTOs\MessageDto.puml
!include .\\.\MessangerWithRoles.WPFClient\DTOs\RoleDto.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\AccountService.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\AuthService.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\GroupsServcie.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\MessagesService.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\NotificationService.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\PersonalChatsService.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\RequestService.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\RolesService.puml
!include .\\.\MessangerWithRoles.WPFClient\Data\Requests\ServiceResponse.puml
!include .\\.\MessangerWithRoles.WPFClient\Data\Requests\SocketResponse.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\AccountLogin.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\Chat.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\ChatMember.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\ChatPermission.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\ChatType.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\CreationAccount.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\FriendRelation.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\Message.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\Role.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\RoleWithPermissions.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\User.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Models\UserRoleRalations.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\AccountSettingsViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\AuthorizationWindowViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\ChatPageViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\ChatViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\CreatePersonalChatViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\FriendsPageViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\GroupPageViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\GroupViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\LoginPageViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\MainWindowViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\RegisterPageViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\RoleAssignmentViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\RolePermissionSettingsViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\RoleToConfigureViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\UserViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\EventBusModule\EventBus.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\EventBusModule\EventBusDefinitions.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\EventBusModule\EventBusHandler.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\ServiceLocatorModule\IService.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\ServiceLocatorModule\ServiceLocator.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Infrastracture\Commands\LambdaCommand.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\ViewModels\Base\BaseViewModel.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\AccountSettings.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\FriendsPage.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\Windows\AuthorizationWindow.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\Windows\MainWindow.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\App.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\App.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\GeneratedInternalTypeHelper.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\GeneratedInternalTypeHelper.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MessengerWithRoles.WPFClient.AssemblyInfo.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MessengerWithRoles.WPFClient_c3hdkhaz_wpftmp.AssemblyInfo.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\EventBusModule\EventBusArguments\ChatDataIEventBusArgs.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\EventBusModule\EventBusArguments\EventBusArgs.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\EventBusModule\EventBusArguments\GroupDataIEventBusArgs.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\EventBusModule\EventBusArguments\IEventBusArgs.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\EventBusModule\EventBusArguments\TextMessageEventBusArgs.puml
!include .\\.\MessangerWithRoles.WPFClient\Services\EventBusModule\EventBusArguments\UserControlEventBusArgs.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Infrastracture\Commands\Base\Command.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\Authorizations\LoginPage.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\Authorizations\RegisterPage.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\ChatSettingsPages\ChatSettings.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\ChatSettingsPages\RoleEditSettings.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\ChatSettingsPages\RoleListSettings.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\Groups\CreateGroupPage.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\Groups\GroupPage.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\PersonalChats\ChatPage.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\MVVM\Views\UserControls\PersonalChats\CreatePersonalChatPage.xaml.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\AccountSettings.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\AccountSettings.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\FriendsPage.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\FriendsPage.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\Windows\AuthorizationWindow.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\Windows\AuthorizationWindow.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\Windows\MainWindow.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\Windows\MainWindow.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\Authorizations\LoginPage.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\Authorizations\LoginPage.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\Authorizations\RegisterPage.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\Authorizations\RegisterPage.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\ChatSettingsPages\ChatSettings.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\ChatSettingsPages\ChatSettings.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\ChatSettingsPages\RoleEditSettings.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\ChatSettingsPages\RoleEditSettings.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\ChatSettingsPages\RoleListSettings.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\ChatSettingsPages\RoleListSettings.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\Groups\CreateGroupPage.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\Groups\CreateGroupPage.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\Groups\GroupPage.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\Groups\GroupPage.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\PersonalChats\ChatPage.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\PersonalChats\ChatPage.g.i.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\PersonalChats\CreatePersonalChatPage.g.puml
!include .\\.\MessangerWithRoles.WPFClient\obj\Debug\net5.0-windows7.0\MVVM\Views\UserControls\PersonalChats\CreatePersonalChatPage.g.i.puml
@enduml
